### ISSUE TITLE
npm clean clean-dependency?

### ISSUE THREAD

**Issue by contextlimit** [sectore/react-native-redux-counter-es6#1]
It mentions `npm clean clean-dependency` in the README, but I don't see that this NPM command exists. Any idea?

**Comment by sectore** [comment]
You are right. It is a typo and should be `npm run clean-dependency`. I have fixed the README ;)

**Comment by contextlimit** [comment]
I'm still not sure that's an official command. Is it something custom you found somewhere? Mind sharing?

**Comment by sectore** [comment]
At the `package.json` you will find what the `clean-dependency` script does. For more information about the idea behind it (incl. the original author) please check the `README.md`, too ;)

**Comment by contextlimit** [comment]
Ah I got it. Thanks much :)
